-- =============================================================================
-- 0010_character_count_target.sql — add 'character_count' as a target type
-- =============================================================================
-- Same manual-entry mechanic as word_count/study_hours: the student types
-- their own count each log, nothing auto-counts real report text. It's a
-- floor to reach, not a ceiling — same target_amount semantics already
-- established for the other numeric types.
--
-- No prior migration has altered this CHECK constraint, so its autogenerated
-- name isn't confirmed anywhere in this repo. Rather than hardcode a guessed
-- name (e.g. targets_target_type_check) and risk silently targeting the
-- wrong constraint, look it up by definition and re-add it under a stable,
-- explicit name so future migrations have a confirmed name to reference.
-- =============================================================================

do $$
declare
  constraint_name text;
begin
  select conname into constraint_name
  from pg_constraint
  where conrelid = 'public.targets'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) like '%target_type%';

  if constraint_name is null then
    raise exception 'Could not find the target_type CHECK constraint on public.targets';
  end if;

  execute format('alter table public.targets drop constraint %I', constraint_name);
end $$;

alter table public.targets
  add constraint targets_target_type_check
  check (target_type in ('task', 'word_count', 'study_hours', 'character_count'));
